-- Show me the product name and the category name.

-- products -- Product Name
-- linkage: categoryID
-- Category -- category Name

--tableName.columnName

--Syntax:
select
from table1
join table2
on table1.key = table2.key

-- Show me the product name and the category name.
select*
from `e1.products`
limit 5


select *
from `e1.categories`
limit 5

alter table `e1.categories`
rename column string_field_0 to CategoryID

alter table `e1.categories`
rename column string_field_1 to CategoryName

select
  p.ProductID,
  p.ProductName,
  c.CategoryID,
  c.CategoryName
from `e1.categories` as c
join `e1.products` as p
on c.categoryID = p.categoryID


--Display products belonging to the Electronics category.
select
  p.ProductID,
  p.ProductName,
  c.CategoryID,
  c.CategoryName
from `e1.categories` as c
join `e1.products` as p
on c.categoryID = p.categoryID
where c.CategoryName = "Electronics"



--Display products with their category names, sorted by MRP from highest to lowest.
select
  p.ProductID,
  p.ProductName,
  c.CategoryID,
  c.CategoryName,
  MRP
from `e1.categories` as c
join `e1.products` as p
on c.categoryID = p.categoryID
order by MRP desc

-- Display ProductName, CategoryName and discount amount.

select
  p.ProductID,
  p.ProductName,
  c.CategoryID,
  c.CategoryName,
  p.MRP - p.SellingPrice as discount_amt
from `e1.categories` as c
inner join `e1.products` as p
on c.CategoryID = p.CategoryID


--Display each product along with its supplier name and supplier state.

select*
from `e1.suppliers`
limit 5

select *
from `e1.products`
limit 5

select
  p.ProductID,
  p.ProductName,
  s.SupplierID,
  s.State,
from `e1.products` as p
inner join `e1.suppliers` as s
on p.SupplierID = s.SupplierID

--Display all cancelled customer orders along with customer name and city.
select *
from `e1.orders`
limit 5

select distinct Status
from `e1.orders`

select *
from `e1.customers`
limit 5

select
  o.OrderID,
  c.CustomerID,
  c.Name,
  c.City
from `e1.orders` as o
inner join `e1.customers` as c
on o.CustomerID = c.CustomerID
where o.Status = "Cancelled"


-- Calculate total sales value for every order.
select *
from `e1.order_items`
limit 5

select
  OrderID,
  sum(Total) as total_value
from `e1.order_items`
group by OrderID
order by OrderID

select
  o.OrderID,
  sum(oi.Total) as total_sales
from `e1.orders` as o
inner join `e1.order_items` as oi
on o.OrderID = oi.OrderID
group by o.OrderID
order by OrderID

-- Calculate total sales value generated by each customer.
select *
from `e1.order_items`
limit 5

select *
from `e1.products`
limit 5

-- 1. customer name -> customer
-- 2. linkage -> table: orders
-- customerid -> orders + customer
-- orderid -> orders + order_items
-- 3. total sales -> order_items


select
  c.CustomerID,
  sum(oi.Total) as total_sales
from `e1.customers` as c
inner join `e1.orders` as o
  on c.CustomerID = o.CustomerID
inner join `e1.order_items` as oi
  on o.OrderID = oi.OrderID
group by c.CustomerID
order by total_sales desc
