--Product-Wise Sales With Product Name
select *
from `e1.order_items`
limit 5

select *
from `e1.products`
limit 5


select 
  p.ProductID,
  p.ProductName,
  sum(oi.Total) as total_sales
from `e1.order_items` as oi
inner join `e1.products` as p
on oi.ProductID = p.ProductID
group by p.ProductID,p.ProductName


--Category wise total sales
select *
from `e1.order_items`
limit 5

select *
from `e1.products`
limit 5

select 
  c.CategoryID,
  c.CategoryName,
  sum(oi.Total) as total_sales
from `e1.order_items` as oi
inner join `e1.products` as p
on oi.ProductID = p.ProductID
inner join `e1.categories` as c
on p.CategoryID = c.CategoryID
group by c.CategoryID,c.CategoryName
order by total_sales desc

--Calculate total sales generated by products from each supplier

select *
from `e1.order_items`
limit 5

select *
from `e1.products`
limit 5

select *
from `e1.suppliers`
limit 5


select 
  s.SupplierID,
  s.SupplierName,
  sum(oi.Total) as total_sales
from `e1.order_items` as oi
inner join `e1.products` as p
on oi.ProductID = p.ProductID
inner join `e1.suppliers` as s
on s.SupplierID = p.SupplierID
group by s.SupplierID, S.SupplierName
order by total_sales desc

--Find products with no sales
select *
from `e1.order_items`
limit 5

select *
from `e1.products`
limit 5

select *
from `e1.suppliers`
limit 5

select
  p.ProductID,
  p.ProductName,
  sum(oi.Total) as sales
from `e1.products` as p
left join `e1.order_items` as oi
  on p.ProductID = oi.ProductID
where oi.ProductID is null
group by p.ProductID, p.ProductName


--Customers who registered but have never placed an order.
select
  c.Name,
  c.CustomerID,
  o.CustomerID,
  o.OrderID
from `e1.customers` as c
left join `e1.orders` as o
  on c.CustomerID = o.CustomerID
where o.OrderID is null

--For every customer, show the number of orders they have placed, including customers with zero orders.
select
  c.CustomerID,
  c.Name,
  count(o.OrderID) as no_of_orders
from `e1.customers` as c
left join `e1.orders` as o
  on c.CustomerID = o.CustomerID
group by c.CustomerID, c.Name
order by no_of_orders asc


select
  c.CustomerID,
  c.Name,
  count(o.OrderID) as no_of_orders
from `e1.orders` as o
right join `e1.customers` as c
  on c.CustomerID = o.CustomerID
group by c.CustomerID, c.Name
order by no_of_orders asc


-- For every customer, calculate:

-- Customer ID
-- Customer name
-- Number of orders placed
-- Total amount paid through successful payments only

-- Display only customers whose successful payment amount is greater than ₹50,000.

-- Sort customers from highest to lowest successful payment amount.
select *
from `e1.customers`
limit 5

select *
from `e1.payments`
limit 5

select *
from `e1.orders`
limit 5

select
  c.CustomerID,
  c.Name,
  count(o.OrderID) as no_of_orders,
  sum(p.Amount) as total_amt
from `e1.customers` as c
left join `e1.orders` as o
  on c.CustomerID = o.CustomerID
left join `e1.payments` as p
  on o.OrderID = p.OrderID
where p.Status = "Success"
group by c.CustomerID, c.Name
having total_amt > 50000
order by total_amt desc



