--How many products are there overall
select count(*)
from `e1.products`

--How many products are there in each category
select *
from `e1.products`
limit 5

select
  CategoryID,
  count(*) as No_Of_Products
from `e1.products`
group by CategoryID 

--How many units of each product have been sold
select *
from `e1.order_items`
limit 5

select
  ProductID,
  sum(Quantity) as No_Of_Products
from `e1.order_items`
group by ProductID

--What is total sales value generated by each product
select *
from `e1.order_items`
limit 5

select
  ProductID,
  sum(Total) as Total_Price
from `e1.order_items`
group by ProductID

--What was the average of selling price at which each product was sold
select *
from `e1.order_items`
limit 5

select
  ProductID,
  avg(SellingPrice) as Avg_Selling_Price
from `e1.order_items`
group by ProductID

--What was the highest and lowest Selling Price recorded for each product
select *
from `e1.order_items`
limit 5

select
  ProductID,
  max(SellingPrice) as Max_Selling_Price,
  min(SellingPrice) as Min_Selling_Price
from `e1.order_items`
group by ProductID

--for each of the order status, what is the number of orders for each of the customers
select *
from `e1.orders`
limit 5

select
  CustomerID,
  Status,
  count(*) as total_count
from `e1.orders`
group by CustomerID, Status

---How many inventory records are maintained for each warehouse
select*
from `e1.inventory`

select
  WarehouseID,
  sum(Stock) as total_stock_count
from `e1.inventory`
group by WarehouseID

--How many order statuses handled by employee
select*
from `e1.orders`
limit 5

select
  EmployeeID,
  Status,
  count(*) as no_of_employees
from `e1.orders`
group by EmployeeID, Status

--How many products in each category have an MRP above rs 20,000.
select*
from `e1.products`
limit 5

select
  CategoryID,
  count(*) as total_products
from `e1.products`
where MRP>2000
group by CategoryID

--What is total quantity sold for each products when quantity is greater than 1
select*
from `e1.order_items`
limit 5

select
  ProductID,
  sum(Quantity) as total_products
from `e1.order_items`
where Quantity>1
group by ProductID

--What is average amount payment for each payment method among succesful payments
select *
from `e1.payments`
limit 5

select distinct PaymentID
from `e1.payments`

select 
  Method,
  round(avg(Amount),2) as avg_payment
from `e1.payments`
where Status = "Success"
group by Method