-- Find the top 10 products by total sales value.

-- Display:

-- ProductID
-- ProductName
-- CategoryName
-- SupplierName
-- Number of times the product appeared in order items
-- Total quantity sold
-- Total sales value
-- Average selling price


select
  p.ProductID,
  p.ProductName,
  c.CategoryName,
  s.SupplierName,
  count(oi.OrderID) as no_of_records,
  sum(oi.Quantity) as total_qty,
  sum(oi.Total) as total_sales,
  avg(oi.sellingprice) as avg_selling_price
from `e1.products` as p
inner join `e1.categories` as c
  on p.CategoryID = c.CategoryID
inner join `e1.suppliers` as s
  on p.SupplierID = s.SupplierID
inner join `e1.order_items` as oi
  on p.ProductID = oi.ProductID
group by
  p.ProductID,
  p.ProductName,
  c.CategoryName,
  s.SupplierName
having total_sales > 100000
order by total_sales desc
limit 10

-- Consider only products having an MRP greater than ₹2,000.

-- For every category, calculate:

-- CategoryID
-- CategoryName
-- Number of qualifying products
-- Average MRP of qualifying products
-- Maximum MRP
-- Minimum MRP

-- Display only categories having more than 2 qualifying products.

-- Sort by average MRP from highest to lowest.

select *
from `e1.products`



select
  c.CategoryID,
  c.CategoryName,
  count(p.ProductID) as no_of_pdt,
  round(avg(MRP),2) as avg_mrp,
  max(MRP) as max_mrp,
  min(MRP) as min_mrp
from `e1.categories` as c
inner join `e1.products` as p
on p.CategoryID = c.CategoryID
where p.MRP >2000
group by 
  c.CategoryID,
  c.CategoryName
having no_of_pdt > 2
order by avg_mrp desc

-- Find all customers who have never placed an order.

-- Display:

-- CustomerID
-- Customer name
-- City
-- State

-- Sort the result alphabetically by customer name.
select *
from `e1.orders`
limit 5



select
  c.CustomerID,
  c.Name,
  c.City,
  o.OrderID
from `e1.customers` as c
left join `e1.orders` as o
on c.CustomerID = o.CustomerID
where OrderID is null
order by c.Name asc

-- For every supplier, calculate:

-- SupplierID
-- SupplierName
-- Number of products supplied
-- Average MRP of their products
-- Total sales generated by their products
-- Total quantity sold

-- Include suppliers even if their products have never been sold.

-- For suppliers with no sales, display the sales and quantity as 0.

-- Sort suppliers by total sales from highest to lowest.
select
  s.SupplierID,
  s.SupplierName,
  count(distinct p.ProductID) as no_of_pdt,
  round(avg(p.MRP),2) as avg_mrp,
  coalesce(sum(oi.Total),0) as total_sales,
  coalesce(sum(oi.Quantity),0) as total_qnt
from `e1.suppliers` as s
left join `e1.products` as p
on p.SupplierID = s.SupplierID
left join `e1.order_items` as oi
on oi.ProductID = p.ProductID
group by
  s.SupplierID,
  s.SupplierName
order by total_sales desc
