-- For every warehouse, calculate:

-- WarehouseID
-- Warehouse name
-- Number of orders handled
-- Total quantity of products sold
-- Total sales value

-- Include warehouses even if they have no orders.

-- Display only warehouses where the total sales value is greater than ₹2,00,000.

-- Sort from highest to lowest total sales.

select *
from `e1.warehouses`
limit 5

select *
from `e1.inventory`
limit 5


select
  w.WarehouseID,
  w.Warehouse,
  count(distinct o.OrderID) as no_of_orders,
  coalesce(sum(oi.Quantity),0) as total_qnt,
  coalesce(sum(oi.Total),0) as total_sales
from `e1.warehouses` as w 
left join `e1.orders` as o
on w.WarehouseID = o.WarehouseID
left join `e1.order_items` as oi
on o.OrderID = oi.OrderID
group by
  WarehouseID,
  Warehouse
having total_sales > 200000
order by total_sales desc

-- Calculate the total sales value generated by every customer. -->order_items

-- Then display only those customers whose total spending is greater than the average customer spending-->orders

-- Display:

-- CustomerID
-- Customer name
-- Total spending

-- Sort from highest spending to lowest.



select 
  c.CustomerID,
  c.Name,
  sum(oi.Total) as total_sales
from `e1.customers` as c
inner join `e1.orders` as o
on c.CustomerID = o.CustomerID
inner join `e1.order_items` as oi 
on o.OrderID = oi.OrderID
group by
  c.CustomerID,
  c.Name
having total_sales > (
                      select
                      round(avg(total_sales),2) as avg_sales
                    from(select
                          o.CustomerID,
                          sum(oi.Total) as total_sales
                        from `e1.orders` as o
                        inner join `e1.order_items` as oi 
                        on o.OrderID = oi.OrderID
                        group by
                          o.CustomerID)
                    )
order by total_sales desc


-- For every product, calculate its total sales value. -->order_items

-- Display only products whose total sales value is greater than the average total sales value of products belonging to the same category.-->subquery

-- Display:

-- ProductID
-- ProductName
-- CategoryName -->category
-- TotalSales

-- Sort by total sales from highest to lowest.

select
  p.ProductID,
  p.ProductName,
  c.CategoryName,
  sum(oi.Total) as total_sales
from `e1.products` as p
inner join `e1.order_items` as oi 
on p.ProductID = oi.ProductID
inner join `e1.categories` as c
on c.CategoryID = p.CategoryID
group by 
  p.ProductID,
  p.ProductName,
  p.CategoryID,
  c.CategoryName
having total_sales > (
                      select
                        round(avg(total_sales),2)
                      from (
                            select
                              p1.ProductID,
                              sum(oi.Total) as total_sales
                            from `e1.products` as p1
                            inner join `e1.order_items` as oi
                            on p1.ProductID = oi.ProductID
                            where p1.CategoryID = p.CategoryID
                            group by p1.ProductID
                            )

                      )
order by total_sales desc

-- categorise customers as
-- 18-20 : genz,
-- 21-40 : adult,
-- 41 onwards : senior_citizen

select
  CustomerID,
  Age,
  Name,
  case
    when Age >= 18 and Age <= 20 then "GenZ"
    when Age >= 21 and Age <= 40 then "Adult"
    else "Senior_Citizen"
  end as age_group
from `e1.customers` as c



-- For every order, calculate the total order value by adding the Total column from order_items.

-- Then classify each order as:

-- High Value -> Total order value >= ₹50,000
-- Medium Value -> Total order value between ₹20,000 and ₹49,999
-- Low Value -> Total order value < ₹20,000

-- Display:

-- OrderID
-- OrderDate
-- CustomerName
-- TotalOrderValue
-- OrderCategory

-- Show the highest-value orders first.

select

