--What is the avergae selling price of products
select*
from `e1.products`

select avg(SellingPrice)
from `e1.products`

select avg(SellingPrice) as avg_selling_price
from `e1.products`

--The Finance team wants a summary of all the transaction
select
  count(*) as no_of_payment,
  sum(amount) as total_payment_amount,
  avg(amount) as avg_payment,
  min(amount) as min_payment,
  max(amount) as max_payment
from `e1.payments`

--Give me the count of productswithin each category
select 
CategoryID,
  count(*) as product_count
from `e1.products`
group by CategoryID

--How many units of each product have been sold
select*
from `e1.order_items`

select 
  ProductID,
  sum(Quantity) as total_quantity
from `e1.order_items`
group by productID

--What is total sales value generated by each product
select 
  ProductID,
  sum(Total) as Selling_Price
from `e1.order_items`
group by ProductID

--Avg Selling Price at which each product was sold.
select 
  ProductID,
  avg(SellingPrice) as Avg_Selling_Price
from `e1.order_items`
group by ProductID

-- Product Sale summary - For every product what is statistics summary
select
  ProductID,
  count(*) as Total_orders,
  sum(Total) as total_sales,
  avg(SellingPrice) as avg_sales,
  min(Total) as min_sales,
  max(Total) as max_sales
from `e1.order_items`
group by ProductID

--For each customer, how many orders are there for each of their different order status
select
  *
from `e1.orders`
limit 5

select
  CustomerID,
  Status,
  count(*) as no_of_orders
from `e1.orders`
group by status,CustomerID